language: python

branches:
  only:
  - develop
  
install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.42.2/hugo_0.42.2_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
    - hugo

deploy:
  provider: pages
  local-dir: public
  target-branch: master
  skip-cleanup: true
  github-token: 
    secure: "GWdltyBLtbDGTONeKfw7dXn5rr2I1g6PSCWki9QijEkqBm4KrcvNGXgFnUYtA3sL3Qhv9XeQd+BLX7SFiSwMSzImfktMmcpizNDw7LH7CjXiFxrbqxPfgZBj5uNje+PzwzJmSXM3VUfaLzYLjO78f2gLrfFiFkZLyOVhFipEDa/5z27Xx8CH/oHfOeI3K0OAHuYEhWxIXmlVSZ2anp2HId39qbgyc5usrrX26NLgCJWWr4SOhm4Fb83vjFOQGi6ByzAC6iktBNnV27EkYm/ahSM6Fpv10krpQU6d4JaNdrgpl7OsgVZKQaAsR4cUIAZC+7UMayb2pmH5OMk7gziZnnFfOhTn21LdmP6uacfON7i3ngqPzrfMZY0cCIYcFXdyuP4bnTioLYvEju3YgIA4EM6vbBm23XjDhflSsOTAmORFMp5rVNbjX/naNEvJpUnwX4Jgs7lFl8Lyxe378hs9FztRnq9OA8ppK5MeAXaY4OtbQSPiB/WyLXG53pEAR85tuKmn3msQP8e0KmRE8aGepH8jwr9YZkcbW6LxfevNJf9ecUsRZqzEt6Y5EbSdW6F4aht97ZR4bc3c4hldKTXvgTY6cS4YLOybeHCWyqqGHeA5AMf9E5HikBvpcgb/+IhFq4BIAbNl2od1zhOxmw8NHTVS5rPC9leMuCpMj5YhY3U="
  keep-history: true
  on:
    branch: develop
