baseURL = "https://astromechza.github.io/"
languageCode = "en-us"
title = "AstromechZA"
theme = "kiera"

copyright = "Copyright &copy; 2018 - Ben Meier"
canonifyurls = true
paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Ben Meier"
    github = "AstromechZA"
    twitter = "@benmeier_"

[params]
    tagline = "My Mind on Code"
